name: Create Repository

on:
  workflow_dispatch: {}
permissions: write-all

jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: pip install PyGithub

      - name: Create Repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            import sys
            from github import Github
            import os
            import requests
            import json
              token = os.getenv('GH_TOKEN')
              g = Github(base_url="https://api.github.com/repos/mybhadre/", login_or_token='token')
              user = g.get_user()
              repo = user.create_repo(new_repo)
