name: Create Repository

on:
  workflow_dispatch: {}
permissions: write-all

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: pip install PyGithub

      - name: Create Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          python create_repo.py
